spring.application.name=athena-os
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

# Swagger
spring-doc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

# Seed
seeds.enabled=${SEEDS_ENABLE}

# Email
spring.mail.host=${SMTP_HOST}
spring.mail.port=${SMTP_PORT}
spring.mail.username=${SMTP_EMAIL}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.properties.mail.smtp.connectionpool=true
spring.mail.properties.mail.smtp.connectionpoolsize=5
spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2

